/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MetricCard: typeof import('./components/MetricCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./components/SectionCard.vue')['default']
    SimpleChart: typeof import('./components/SimpleChart.vue')['default']
    StatusTag: typeof import('./components/StatusTag.vue')['default']
  }
}
